# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: bhp_kenya
val_db_name: bhp_kenya
num_classes: 39
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.3300, 0.3193, 0.2634] #[0.485, 0.456, 0.406]
      std: [0.1704, 0.1739, 0.1691] #[0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.3300, 0.3193, 0.2634] #[0.485, 0.456, 0.406]
      std: [0.1704, 0.1739, 0.1691] #[0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100 #100
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
